spring.application.name=Climalert-DDSI-K3101-Marcos-Jose-Belfiore

weather-api.base-url=https://api.weatherapi.com/v1
weather-api.api-key=${TU_WEATHER_API_KEY}
weather-api.location=Buenos Aires

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${TU_EMAIL}
spring.mail.password=${TU_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true