spring.application.name=Climalert-DDSI-K3101-Marcos-Jose-Belfiore

weather-api.base-url=https://api.weatherapi.com/v1
weather-api.api-key=ac4d8de287354ddda33151433260607
weather-api.location=Buenos Aires